#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  
  [[blocks.segments]]
    type = "os"
    style = "plain"
    foreground = "#26C6DA"
    background = "transparent"
    template = "{{ if .WSL }}WSL at {{ end }}{{.Icon}}  "

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '{{ .Path }}'
    
    [blocks.segments.properties]
      style = 'agnoster_short'
      max_depth = 2  

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'magenta'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      commit_icon = '@'
      fetch_status = true

 [[blocks]]
    type = 'rprompt'
    overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 500


[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}magenta{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[properties]
always_enabled = true

[transient_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❯❯ '
